### ISSUE TITLE
Can't handle Geni Gedcom with FORM

### ISSUE THREAD

**Issue by Sternbach-Software** [elliotchance/gedcom#329]
```
./gedcom query -gedcom export-Bio.ged -gedcom ancestry.ged -format gedcom \                                                
  'MergeDocumentsAndIndividuals(Document1, Document2)' > merged.ged
panic: indent is too large - missing parent? at line 18979: 4 FORM txt

goroutine 1 [running]:
github.com/elliotchance/gedcom.(*Decoder).Decode(0xc000171c98)
	/Users/shmuel/GoLandProjects/gedcom/decoder.go:149 +0x788
github.com/elliotchance/gedcom.NewDocumentFromGEDCOMFile({0x205912706?, 0x205912772?})
	/Users/shmuel/GoLandProjects/gedcom/document.go:238 +0x165
main.runQueryCommand()
	/Users/shmuel/GoLandProjects/gedcom/cmd/gedcom/query.go:52 +0x76c
main.main()
	/Users/shmuel/GoLandProjects/gedcom/cmd/gedcom/main.go:47 +0x156

```

```

0 @I4059803058540122349@ INDI
1 NAME private
2 GIVN private
2 _MARNM private
2 NICK private
2 NICK private
1 SEX M
1 BIRT
2 DATE private
2 PLAC private
2 ADDR
1 DEAT
2 DATE private
1 FAMC @F4085785484380027007@
1 FAMS @F4059810089080022028@
1 RFN geni:PRIVATE_ID
1 SUBM @S4055133865470029013@
1 SOUR
2 DATA
3 DATE private
3 TEXT Date of Birth
3 TEXT private
2 OBJE
3 FILE https://media.geni.com/private.pdf
4 FORM pdf
3 TITL private.pdf
1 CHAN
2 DATE private
3 TIME private
```

**Comment by elliotchance** [comment]
Can you mark which line is 18979?

**Comment by Sternbach-Software** [comment]
```4 FORM pdf```
